### ISSUE TITLE
SPARQL error

### ISSUE THREAD

**Issue by surainbr** [bio-ontology-research-group/pathophenodb#12]
Dear PathoPhenoDB Team,
It seems the SPRARQL query function is broken. When the example query content was submitted, it returned "502 Bad Gateway" info. 
I also downloaded the data, and made query (#EX1) locally with command line "sparql --data=patho_pheno.v3.nt --query=query.rq", only the header information was returned.

Thank you very much!
All the best,
Surainbr

**Comment by aliraza995** [comment]
Dear Surainbr,

Thanks for reporting the issue. We have fixed the issue. Sparql query functions are now working.

Thanks,

Ali
