### ISSUE TITLE
Download DB v3 fail

### ISSUE THREAD

**Issue by regnon1203** [bio-ontology-research-group/pathophenodb#13]
hello

I would like to download the database but the link looks broken and no data are dowloaded.

Thanks you for your support
Best regards
Regis

**Comment by aliraza995** [comment]
Dear Regis,

Thanks for reporting the issue. We have fixed the download issue.

Thanks,

Regards,
Ali

**Comment by regnon1203** [comment]
Thanks you for your prompt support
Regis
