### ISSUE TITLE
Searching in the Database

### ISSUE THREAD

**Issue by GAIN-registry** [bio-ontology-research-group/pathophenodb#7]
Dear PathoPhenoDB Team,
It seams for me that the search function is broken. I use Firefox for browsing and it seams I can enter a search request but I cannot press 'enter'  - well when I do, nothing happens.
Thank you a lot in advance!
All the best,
Paulina

![grafik](https://user-images.githubusercontent.com/57149307/73005016-86c5ec80-3e08-11ea-8d33-be4ed57d0d82.png)

**Comment by aliraza995** [comment]
Fixed. Thanks for reporting it.
